### ISSUE TITLE
acii2d经常检索失败，重复多次才成功

### ISSUE THREAD

**Issue by mhy9989** [pcrbot/picfinder_take#13]
搜索ascii2d老是第一次或第二次不行，反复搜几次才能成功，怀疑有时候不能正常获取网页数据，但不知如何解决。

**Comment by assassingyk** [comment]
既然不能稳定复现那显然主要是你的网络环境的问题……
（也可以考虑加几次自动retry但是现在单次搜图速度已经挺慢的了再加retry感觉会更严重）
