### ISSUE TITLE
进入连续搜图模式时报错

### ISSUE THREAD

**Issue by SanaChitose** [pcrbot/picfinder_take#16]
![图片](https://user-images.githubusercontent.com/102790983/179652002-67cb041e-9215-4971-8569-12e7caa8cc9f.png)
识图+图片的话没有问题

**Comment by assassingyk** [comment]
你确定你用的是本插件吗……源码里都没有你报错的这句……是不是隔壁哪个其他的搜图插件啊）

**Comment by SanaChitose** [comment]
> 你确定你用的是本插件吗……源码里都没有你报错的这句……是不是隔壁哪个其他的搜图插件啊）

实在抱歉，不小心把另一个插件的注释取消了，给大佬添麻烦了┭┮﹏┭┮！

**Comment by SanaChitose** [comment]
（但是最近风控好厉害啊，合并转发模式都一直被风控

**Comment by assassingyk** [comment]
这没办法，你得找腾讯去）

我三个号有两个可以转发，一个完全发不出来
实在不行就关了合并转发和预览图用纯文本回复罢）
