### ISSUE TITLE
在群内搜图，如果开启合并转发，无返回结果

### ISSUE THREAD

**Issue by allenx555** [pcrbot/picfinder_take#4]
稍微看了一下，直到 `bot.send_group_forward_msg(group_id=ev['group_id'],` messages=chain)` 前都有正确返回，看上去像是send_group_forward_msg和消息格式相关的问题？

**Comment by assassingyk** [comment]
我这边使用一直都正常的，建议确认一下go那边有没有报错或者风控。

合并转发消息目前似乎有时候会遇到某种“隐性风控”，没有风控报错，但是发不出来，这种一般只能试试多挂一段时间、换device信息或者换服务器ip。

我自己的服务器最早也是发不出来，但是个人电脑端调试能发出来，后来过了几个月服务器也突然能发出来了）
