### ISSUE TITLE
关于撤回问题

### ISSUE THREAD

**Issue by jiyemengmei** [pcrbot/picfinder_take#7]
是否可以添加个定时撤回搜索结果的功能

**Comment by assassingyk** [comment]
撤回啊……我是觉得撤回属于自欺欺人的功能……对于腾讯的ai自动审查肯定是没效果的（发送的时候就已经审查过了），对于内鬼手动举报后的腾讯人工审查应该也是没用的（后台对你撤回过什么消息肯定有记录），所以干脆写的时候就没加这个功能……

需要的话也可以加，等我什么时候有空了加一下罢（或者哪位大佬写好pr一下也行）~~（咕咕咕.jpg）~~
