### ISSUE TITLE
使用最新版 go-cqhttp消息无法正确发送

### ISSUE THREAD

**Issue by Rcrafte22** [pcrbot/picfinder_take#8]
go-cqhttp输出如下

[2021-12-05 07:57:50] [WARNING]: 警告: 非法 Forward node 将跳过. uin: 261358339 name:  content count: 7
[2021-12-05 07:57:55] [WARNING]: 警告: 非法 Forward node 将跳过. uin: 261358339 name:  content count: 7

**Comment by assassingyk** [comment]
我自己用go的v1.0.0-beta8-fix1的linux_amd64和windows_amd64都没有复现过，请提供更多信息……

**Comment by Rcrafte22** [comment]
没有更多信息能提供了，我HoshinoBot九个月没有更新过了，和这个会有关系吗？

**Comment by assassingyk** [comment]
按说没有，调用api需求的格式按说只和go那边协议端有关……我再看看go文档罢

**Comment by assassingyk** [comment]
看了下可能是go是beta5的时候改了下合并转发的要求，把字段名从uin改成user_id了（不过他给的示例里还是没改），不过估计是做了旧格式的兼容所以一直没发现？

你把init.py的247行那里的“uin”改成“user_id”试试看看问题解决没有。

**Comment by Rcrafte22** [comment]
好的，现在出去了，晚点回来试试

**Comment by WindStill** [comment]
为啥最新的代码，还是会提示这个uin问题，我看代码里没有uin啊

**Comment by WindStill** [comment]
go-cqhttp 版本是 1.0.0-beta8-fix2

**Comment by Rcrafte22** [comment]
> go-cqhttp 版本是 1.0.0-beta8-fix2

我已经好久没摸过pcrbot了，我记得当时好像是用了旧版的go-cqhttp，但是现在应该不能用了

**Comment by WindStill** [comment]
> 

有没有办法拯救一下。

插件里报错：
![983DA4648F1F9BDC0B54CFBA6D5D93CF](https://user-images.githubusercontent.com/958456/171542437-61c3dce9-7ce8-4d77-a4c1-8142ba38334d.png)

go-cqhttp 里警告跟上面相同

**Comment by Rcrafte22** [comment]
> > 
> 
> 有没有办法拯救一下。
> 
> 插件里报错： ![983DA4648F1F9BDC0B54CFBA6D5D93CF](https://user-images.githubusercontent.com/958456/171542437-61c3dce9-7ce8-4d77-a4c1-8142ba38334d.png)
> 
> go-cqhttp 里警告跟上面相同

有没有改过代码？我找了个旧bot试了一下还能正常用，试试重新clone一下吧。

**Comment by assassingyk** [comment]
你先换最新版v1.0.0-rc1试下？我目前从来没遇到过这个情况……

看go的代码里也确实是同时兼容了uin和user_id两个字段名，按说不该有问题的 https://github.com/Mrs4s/go-cqhttp/blob/54dbccf63cd9a7354144386598a999b842ed213e/coolq/api.go#L842

**Comment by Rcrafte22** [comment]
> go-cqhttp 版本是 1.0.0-beta8-fix2

更新一下go-cqhttp吧

**Comment by assassingyk** [comment]
或者和go的平台有关系？我用过的是windows_amd64和linux_amd64，按说从一个源码编译出来的也不该有区别吧……

**Comment by WindStill** [comment]
好的。我试试最新的1.0.0-rc1

**Comment by assassingyk** [comment]
> 默认昵称？好像没设置过，在哪里设置？

就 __bot__.py 里面 NICKNAME 那一项……
等下我加个没给昵称默认用竹竹罢）

**Comment by WindStill** [comment]
> > 默认昵称？好像没设置过，在哪里设置？
> 
> 就 **bot**.py 里面 NICKNAME 那一项…… 等下我加个没给昵称默认用竹竹罢）

最新代码还是那个问题😂

**Comment by WindStill** [comment]
> > 默认昵称？好像没设置过，在哪里设置？
> 
> 就 **bot**.py 里面 NICKNAME 那一项…… 等下我加个没给昵称默认用竹竹罢）

好了，可以了。多谢
